### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by MarcDrexler** [TheKimono/3Commas.Net#20]
Hi,

on some older machines (Windows 7) I get the following error:

```
Error getting response from server: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XCommas.Net.XCommasApi.<GetRawResponse>d__101.MoveNext()
```

I think that problem occurs because TLS 1.0 and 1.1 are deprecated on that OS and the HttpHandler is using the system default for its requests.
Do you have any ideas how to work around this problem?

**Comment by MarcDrexler** [comment]
Ok, since this is a general problem and not a specific 3commas.Net problem, the issue can be closed. We decided to simply update the OS :)
