### ISSUE TITLE
Error converting value "conditional" to type 'XCommas.Net.Objects.SmartTrades.OrderType'

### ISSUE THREAD

**Issue by Jenscaasen** [TheKimono/3Commas.Net#46]
Hi,
i am trying to get a list of my smarttrades with GetSmartTradesAsync. The errormessage is below.

Looking at the Enum it should be fine though:
https://github.com/TheKimono/3Commas.Net/blob/master/XCommas.Net/XCommas.Net/Objects/SmartTrades/OrderType.cs

The latest Version i get from Nuget is 1.0.33 from September 4, while OrderType.cs was changed on September 13.
Can you please publish that version from September 13?

Thanks!

> Could not serialize json to SmartTrade[] : Newtonsoft.Json.JsonSerializationException: Error converting value "conditional" to type 'XCommas.Net.Objects.SmartTrades.OrderType'. Path '[0].position.order_type', line 1, position 556.
>  ---> System.ArgumentException: Requested value 'conditional' was not found.
>    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
>    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at XCommas.Net.XCommasApi.GetResponse[T](XCommasRequest request)

**Comment by Jenscaasen** [comment]
Update: there is a comma missing in the linked file, that is propably stopping the push to nuget.  I am trying to commit the fix

**Comment by Jenscaasen** [comment]
Update 2: problem is fixed in this pull request already:
https://github.com/TheKimono/3Commas.Net/pull/42/commits/782c92304a736565f50e0ccdba8825fa0ffcce32
Pulling that request should also close this issue
